version: "3.8"

services:
  postgres:
    image: postgres:13
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: digimondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "7000:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DATASOURCES_DEFAULT_URL: jdbc:postgresql://postgres:5432/digimondb
      DATASOURCES_DEFAULT_USERNAME: postgres
      DATASOURCES_DEFAULT_PASSWORD: mysecretpassword
    depends_on:
      - postgres

volumes:
  postgres-data:
